%{?!ros_distro:%global ros_distro kilted}
%global pkg_name rqt_controller_manager
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-kilted-rqt-controller-manager
Version:        5.16.0
Release:        1%{?dist}
Summary:        ROS %{pkg_name} package

License:        Apache License 2.0
URL:            http://ros.org/wiki/rqt_controller_manager
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  python%{python3_pkgversion}-devel

%{?bloom_package}

%description
Graphical frontend for interacting with the controller manager.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
Graphical frontend for interacting with the controller manager.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
Graphical frontend for interacting with the controller manager.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%py3_build


%install
%py3_install -- --prefix "%{bloom_prefix}"


%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "^\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Tue Jul 14 2026 Bence Magyar <bence.magyar.robotics@gmail.com> - 5.16.0-1
- Autogenerated by Bloom

* Wed Jul 01 2026 Bence Magyar <bence.magyar.robotics@gmail.com> - 5.15.0-1
- Autogenerated by Bloom

* Tue May 12 2026 Bence Magyar <bence.magyar.robotics@gmail.com> - 5.14.2-1
- Autogenerated by Bloom

* Fri Apr 24 2026 Bence Magyar <bence.magyar.robotics@gmail.com> - 5.14.1-1
- Autogenerated by Bloom
